language: node_js

services:
  - docker

before_install:
  #install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install: true

script:
  - docker build -t registry.heroku.com/frozen-retreat-15997/web .

deploy:
  provider: script
  script:
    bash docker_push
  on:
    branch: scotty_weedcash

# safelist
branches:
  only:
  - master
  - scotty_aaa
  - scotty_actnearn
  - scotty_bloque64
  - scotty_pal
  - scotty_spt
  - scotty_steemcoinpan
  - scotty_weedcash
