language: node_js

services:
  - docker

before_install:
  #install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install: true

script:
  - docker build -t registry.heroku.com/sportstalksocial/web .

deploy:
  provider: script
  script:
    bash docker_push
  on:
    branch: scotty_sports

# safelist
branches:
  only:
  - master
  - scotty_sports
