version: "3.7"
services:
  hive_condenser_stg:
     image: hiveio/condenser:development
     container_name: hive_condenser_stg
     environment:
         VIRTUAL_HOST: staging-blog.hive.ios
         VIRTUAL_PORT: 8080
         LETSENCRYPT_HOST: staging-blog.hive.io
         LETSENCRYPT_EMAIL: certs@hive.io
         SDC_CLIENT_STEEMD_URL: https://api.hive.blog
         SDC_SERVER_STEEMD_URL: https://api.hive.blog
         SDC_SITE_DOMAIN: staging-blog.hive.io
         SDC_IMAGE_PROXY_PREFIX: https://images.hive.blog/
         SDC_UPLOAD_IMAGE_URL: https://images.hive.blog
         SDC_HELMET_CONNECTSRC: "'self' https://api.hive.blog https://staging.hive.blog https://images.hive.blog https://anyx.io"
         WALLET_URL: https://wallet.hive.blog
     networks:
         - reverse-proxy
     restart: always

networks:
    reverse-proxy:
        external:
            name: reverse-proxy
