version: 2
jobs:
  build:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t wallet .
      - run:
          name: Save Docker image
          command: docker save -o wallet.tar wallet
      - persist_to_workspace:
          root: .
          paths:
            - wallet.tar
  build-blackboxtest:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t wallet-blackboxtest blackboxtest/
      - run:
          name: Save Docker image
          command: docker save -o wallet-blackboxtest.tar wallet-blackboxtest
      - persist_to_workspace:
          root: .
          paths:
            - wallet-blackboxtest.tar
  run-blackboxtest:
    docker:
      - image: docker:17-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker images
          command: |
            docker load -i /tmp/workspace/wallet.tar
            docker load -i /tmp/workspace/wallet-blackboxtest.tar
      - run:
          name: Start wallet
          command: |
            docker run -ditp 8080:8080 --name wallet wallet
            sleep 10 # let wallet start
      - run:
          name: Run tests
          command: docker run --network container:wallet wallet-blackboxtest
workflows:
  version: 2
  wallet:
    jobs:
      - build
      - build-blackboxtest
      - run-blackboxtest:
          requires:
            - build
            - build-blackboxtest
